# Generated by Django 3.0.8 on 2020-07-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200726_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('New', 'New')], max_length=100),
        ),
    ]
