# Generated by Django 3.0.8 on 2020-08-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200730_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ips',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='viewer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('used', 'Used')], max_length=100),
        ),
    ]
