# Generated by Django 3.0.8 on 2020-08-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200813_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ips',
        ),
    ]
