# Generated by Django 3.0.8 on 2020-08-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='product',
        ),
    ]
