# Generated by Django 3.0.8 on 2020-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_viewer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('used', 'Used')], max_length=100),
        ),
    ]
