# Generated by Django 3.0.8 on 2020-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200814_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('New', 'New')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.TextField(default=None, unique=True),
        ),
    ]
