# Generated by Django 3.0.8 on 2020-08-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='product',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
