# Generated by Django 3.0.8 on 2020-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_viewer_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('used', 'Used')], max_length=100),
        ),
    ]
