# Generated by Django 3.0.8 on 2020-08-14 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200814_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('New', 'New')], max_length=100),
        ),
    ]
