# Generated by Django 3.0.8 on 2020-08-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20200814_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('used', 'Used')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='product',
        ),
        migrations.AddField(
            model_name='viewer',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
